name: Sync OneDrive Images to GitHub

on:
  workflow_dispatch:
  schedule:
    - cron: '0 11 * * 2,3'  # Runs every Tuesday at 15:00 (11 AM)

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch images from OneDrive
        id: fetch_images
        run: |
          # Set your OneDrive access token
          ONEDRIVE_ACCESS_TOKEN="${{ secrets.ONEDRIVE_ACCESS_TOKEN }}"

          # Fetch images from OneDrive
          response=$(curl -s -X GET "https://graph.microsoft.com/v1.0/users/998e6817-e81a-4c40-a387-34c1ab27b201/drive/items/01KWR5ZX2PEZYK2OZVPFFLVJGAPE4RYQEU/children" \
            -H "Authorization: Bearer $ONEDRIVE_ACCESS_TOKEN")

          echo "$response" > response_log.txt

          # Parse image URLs and names safely
          urls=$(echo "$response" | jq -r '.value[] | select(.file) | .["@microsoft.graph.downloadUrl"] // empty')
          names=$(echo "$response" | jq -r '.value[] | select(.file) | .name // empty')
          echo "ALL names: $names"
          echo "ALL urls: $urls"
          if [[ -z "$urls" || -z "$names" ]]; then
              echo "No images found or error in fetching images."
              exit 1
          fi

          # Download images
          mkdir -p downloaded_images
          paste <(echo "$urls") <(echo "$names") | while IFS=$'\t' read -r url name; do
              # Sanitize filename
              sanitized_filename=$(echo "$name" | tr -dc '[:alnum:]._-')
              sanitized_filename=$(echo "$sanitized_filename" | cut -c1-50)  # Limit to 50 characters

              # Download the image
              if curl -L -o "downloaded_images/$sanitized_filename" "$url"; then
                  echo "Downloaded: $sanitized_filename"
              else
                  echo "Failed to download: $url"
              fi
          done

      - name: Commit images to GitHub
        run: |
          git config --local user.name "biteam2024"
          git config --local user.email "bi.analytics@arthdesignbuild.com"
          if [ -n "$(ls -A downloaded_images)" ]; then
              git add downloaded_images/*
              git commit -m "Add images from OneDrive"
              git push
          else
              echo "No new images to add."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for pushing changes
