name: Sync OneDrive Images to GitHub

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # This runs the workflow every hour (adjust as needed)

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch images from OneDrive
        id: fetch_images
        run: |
          # Set your OneDrive access token and folder path
          ONEDRIVE_ACCESS_TOKEN="${{ secrets.ONEDRIVE_ACCESS_TOKEN }}"
          # FOLDER_PATH="Documents/BKC/BKC%20Input%20Images"  # Change to your folder path

          # Fetch images from OneDrive
          response=$(curl -s -X GET "https://graph.microsoft.com/v1.0/users/998e6817-e81a-4c40-a387-34c1ab27b201/drive/items/01KWR5ZX2PEZYK2OZVPFFLVJGAPE4RYQEU/children" \
            -H "Authorization: Bearer $ONEDRIVE_ACCESS_TOKEN")

          # Print the response for debugging
          # echo "Response: $response"

          # # Check if the response is empty
          # if [[ -z "$response" ]]; then
          #   echo "Failed to fetch images. Response is empty."
          #   exit 1
          # fi

          # # Parse image URLs
          # echo "$response" | jq -r '.value[] | select(.file != null) | .["@microsoft.graph.downloadUrl"]' > image_urls.txt

          # # Download images
          # mkdir -p downloaded_images
          # while read -r url; do
          #   curl -L -o "downloaded_images/$(basename "$url")" "$url"
          # done < image_urls.txt
          echo "$response" > response_log.txt

          # Parse image URLs safely
          urls=$(echo "$response" | jq -r '.value[] | select(.file) | .["@microsoft.graph.downloadUrl"] // empty')
          if [[ -z "$urls" ]]; then
              echo "No images found or error in fetching images."
              exit 1
          fi
          echo "$urls" > image_urls.txt
          
          # Download images
          mkdir -p downloaded_images
          while read -r url; do
              curl -L -o "downloaded_images/$(basename "$url")" "$url"
          done < image_urls.txt

      - name: Commit images to GitHub
        run: |
          git config --local user.name "biteam2024"
          git config --local user.email "bi.analytics@arthdesignbuild.com"
          git add downloaded_images/*
          git commit -m "Add images from OneDrive"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for pushing changes
